name: Publish Alpha
on:
  workflow_dispatch:
    inputs:
      preid:
        description: 'Preid used to publish package. Must be unique per branch.'
        required: true
        default: 'alpha'
      ref:
        description: 'Commit to deploy from. Defaults to branch used for workflow_dispatch action.'
        required: false
        default: ''
jobs:
  publish-alpha:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0' # Need the history to properly select the canary version number
          ref: ${{ github.event.inputs.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - run: ./node_modules/.bin/lerna publish --canary --force-publish=\* --preid ${{ github.event.inputs.preid }} --dist-tag canary --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.DEEPHAVENBOT_NPM_TOKEN }}
